### ISSUE TITLE
How to make Debug.Trace output sane when running a hedgehog test?

### ISSUE THREAD

**Issue by newhoggy** [hedgehogqa/haskell-hedgehog#187]
I'm finding that hedgehog output has a tendency to interleave with and overwrite Debug.Trace output.  Is there a workaround for this?

**Comment by theindigamer** [comment]
Does using the usual printing functions instead of trace functions help? If you're tracing from deep within your application code, it might help to break the test into smaller parts and then print things in between from the test runner. While the stdout will still be interleaved, it should now be in the correct order.

**Comment by thumphries** [comment]
I don't think there's much we can do in this case, since `Debug.trace` is going to print at unpredictable times when your values are forced.

If you're using `Debug.trace` heavily you might be able to make it more deterministic by using `deepseq` before making assertions?

**Comment by joelburget** [comment]
I also have this problem. I wonder, would it be possible to add a "simple" runner which doesn't use concurrent-output, ie just prints to the console? I like @theindigamer's suggestion, though it will take a big refactor in my case, since I'm testing pure code.

**Comment by HuwCampbell** [comment]
What's discussed in #236 should also be applicable for this issue.

**Comment by HuwCampbell** [comment]
Can we mark this as duplicate and close?

**Comment by moodmosaic** [comment]
Closing in favor of #236, where the workarounds are collected.
