### ISSUE TITLE
Wrong version requirement for resourcet

### ISSUE THREAD

**Issue by CaptJakk** [hedgehogqa/haskell-hedgehog#248]
It appears that the dependency `resourcet` requires `> 1.1 && < 1.3` on the most recent version of hedgehog. However the docs strongly imply that you can use hedgehog with tests that use `ResourceT`. However upon further inspection, it is impossible to write this because the version of `resourcet` that is in the dependencies requires a `MonadUnliftIO` constraint in order to use `runResourceT`. This is in contrast to the older version of the library which used `MonadBaseControl IO`. All of this said, it appears that since `TestT` is a wrapper around `ExceptT` and `Writer` it would be impossible to write an instance of `MonadUnliftIO` for it.

So it appears that one of the following courses of action is required:
1. Constrain Hedgehog to a version of `resourcet` that is less than 1.1.9
2. Purge all references to ResourceT from Hedgehog as they are misleading. This obviously leaves the hole for how we run tests that must make use of resourcet, which I would love some advice on if there is any to offer.

**Comment by gwils** [comment]
Hedgehog has the less restrictive upper bound because it needs `resourcet` for its own purposes. `hedgehog` needs `resourcet` to give a `MonadResource` instance to `GenT`, but it doesn't care much which version of `resourcet` is used. The less restrictive bound is helpful for most users.

If you add an upper bound `resourcet < 1.2` to your own project, you'll be able to `runResourceT` in your hedgehog tests.
An example of this is in the `hedgehog-example` subdirectory of this project. Note that the cabal file in that directory uses `resourcet >= 1.1 && < 1.2`.
