### ISSUE TITLE
Compatibility with resourcet (in user code)

### ISSUE THREAD

**Issue by cblp** [hedgehogqa/haskell-hedgehog#284]
# Documentation

https://hackage.haskell.org/package/hedgehog-0.6.1/docs/Hedgehog.html#v:test

> One use case for this is writing tests which use ResourceT:

```
  property $ do
    n <- forAll $ Gen.int64 Range.linearBounded
    test . runResourceT $ do
      -- test with resource usage here
```

# In #248

1. The thought is expressed that it is impossible to implement `instance MonadUnliftIO (TestT IO)`.
2. It is recommended to use an old version of `resourcet`, which is not a viable solution.

# Question

How to solve this contradiction?

**Comment by jystic** [comment]
Ah, apologies, this documentation is out of date, you can use `ResourceT` as follows:

```haskell
  property . hoist runResourceT $ do
    n <- forAll $ Gen.int64 Range.linearBounded
    test $ do
      -- test with resource usage here
```

or like this:

```haskell
  property $ do
    n <- forAll $ Gen.int64 Range.linearBounded
    hoist runResourceT $ do
      -- test with resource usage here
```

The difference (I think, haven't tested it) between the two is that the top one uses the same `ResourceT` lifetime for a given test including shrinking, where as the bottom one uses a new `ResourceT` lifetime for the initial test and for each shrink, which is probably better but often doesn't really matter if it's just to clean up temporary files.

`test` now is mainly used for parallel state machine testing where we need to be able to spawn threads inside a `MonadTest`, for that we use the `MonadBaseControl` instance and `lifted-async`.

I will update the documentation.

**Comment by jystic** [comment]
Ok I have tested this out and I think you are safe to use either approach, it actually will create a resource bracket for each shrink in both cases. It's just if you do regular `IO` before the `forAll` block that it will give you strange behavior.

To understand how this is works I have cooked up this example:

```haskell
bracketLog :: Int -> String -> IO a -> IO a
bracketLog indent x io = do
  appendFile "hedgehog.log" (replicate indent ' ' ++ x ++ " {\n")
  z <- io
  appendFile "hedgehog.log" (replicate indent ' ' ++ "}\n")
  pure z

normalLog :: MonadIO m => Int -> String -> m ()
normalLog indent x = do
  liftIO $ appendFile "hedgehog.log" (replicate indent ' ' ++ x ++ "\n")

prop_example :: Property
prop_example =
  property . hoist (bracketLog 0 "before:hoist") $ do
    normalLog 2 "before"

    values0 <- forAll $
     Gen.list (Range.linear 0 100) $
     Gen.string (Range.constant 1 5) Gen.alpha

    normalLog 2 "forAll"

    hoist (bracketLog 2 "after:hoist") . hoist runResourceT $ do
      normalLog 4 "after"

    ...
```

We get the following log output during normal testing:

```
before:hoist {
  before
  forAll
  after:hoist {
    after
  }
}
```

Then during shrinking, the logs change to this:

```
before:hoist {
  forAll
  after:hoist {
    after
  }
}
```

So you can see, the `hoist` continues to work as expected, but actions taken prior to the `forAll` block are not rerun.

Because of how `Gen.list` and `Gen.string` work during shrinking, we also get some discarded / degenerate cases which look like this:

```
before:hoist {
}
```

If we change the property to use `replicateM` instead then the degenerate cases disappear:

```haskell
prop_unix_sort :: Property
prop_unix_sort =
  property . hoist (bracketLog 0 "before:hoist") $ do
    normalLog 2 "before"

    n <- forAll $ Gen.int (Range.linear 0 100)
    m <- forAll $ Gen.int (Range.constant 1 5)
    values0 <- forAll $
      replicateM n $
      replicateM m $ Gen.alpha

    normalLog 2 "forAll"

    hoist (bracketLog 2 "after:hoist") . hoist runResourceT $ do
      normalLog 4 "after"
```

Note, using `replicateM` like this is not recommended as it results in much worse shrinking behavior, but it is useful to understand what is going on.

**Comment by cblp** [comment]
Great! Thanks!

**Comment by jystic** [comment]
I have been tempted to make it so `property` is always in `ResourceT` so you can just use `MonadResource` without even thinking about it, and it shouldn't really affect anyone not using it, in the same way you can write pure properties even though we have `IO` by default. Not sure how popular that would be with some users though :laughing:
