### ISSUE TITLE
No way to see generated values?

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [hedgehogqa/haskell-hedgehog#507]
How to see which values were generated for each of 100 tests?
For example,
Given property:
a <- genA
b<- genB
c<-gen C
a + b + c === x

I need this report:
Test 1
a: 147
b: 584
c: 993

the rest of the tests...

Test 100
a: 12
b: 32
c: 553

All 100 tests passed

P.S. I tried annotate, label, annotateShow, but none of them show anything, no idea how to use them

**Comment by moodmosaic** [comment]
Hedgehog typically abstracts away individual test details to focus on property-based testing. This approach emphasizes verifying properties of code over a range of inputs, rather than examining outputs from individual test cases.

However, if you need to view the values for each test, including the ones that pass, you can use some workarounds. Although it's important to note that these methods are not standard practices in property testing and might clutter the test output.

**Using `putStrLn` for Console Output**

You can use `putStrLn` to print the values directly to the console. This method is straightforward but may interleave your test values with Hedgehog's own output:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Hedgehog
import qualified Hedgehog.Gen as Gen
import qualified Hedgehog.Range as Range
import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)

prop_test_with_trace :: Property
prop_test_with_trace = property $ do
  a <- forAll $ Gen.int (Range.linear 0 1000)
  b <- forAll $ Gen.int (Range.linear 0 1000)
  c <- forAll $ Gen.int (Range.linear 0 1000)

  liftIO $ putStrLn $ "Test : a=" ++ show a ++ ", b=" ++ show b ++ ", c=" ++ show c
  a + b + c === a + b + c  -- Replace with your assertion here.

main :: IO ()
main = do
  result <- checkSequential $ Group "Test Group" [
      ("prop_test_with_trace", prop_test_with_trace)
    ]
  unless result $
    fail "Some tests failed"
```

**Writing to a File**

Alternatively, you can write the output to a file. This approach avoids cluttering the console output and is especially useful when running in environments like GHCi:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Hedgehog
import qualified Hedgehog.Gen as Gen
import qualified Hedgehog.Range as Range
import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import System.IO (withFile, IOMode(WriteMode), hPutStrLn, Handle)

prop_test_with_trace :: Handle -> Property
prop_test_with_trace handle = property $ do
  a <- forAll $ Gen.int (Range.linear 0 1000)
  b <- forAll $ Gen.int (Range.linear 0 1000)
  c <- forAll $ Gen.int (Range.linear 0 1000)

  liftIO $ hPutStrLn handle $ "Test : a=" ++ show a ++ ", b=" ++ show b ++ ", c=" ++ show c
  a + b + c === a + b + c  -- Replace with your assertion here.

main :: IO ()
main = withFile "test_output.txt" WriteMode $ \handle -> do
  result <- checkSequential $ Group "Test Group" [
      ("prop_test_with_trace", prop_test_with_trace handle)
    ]
  unless result $
    fail "Some tests failed"
```

Please note that these approaches are more of a debugging or inspection tool and may not align with the typical philosophy of property-based testing. They are useful for gaining insights into the specific values being tested, particularly for debugging purposes.

Let us know if you need further clarification or assistance.

**Comment by ildar-shaymukhametov** [comment]
Thanks for the answer! 
yes, I just needed to debug values
In discord I was told to use collect
So I just wrote “collect (a,b,c)” as the last line
It was enough for debugging

**Comment by moodmosaic** [comment]
Great! Which discord? 👀

**Comment by ildar-shaymukhametov** [comment]
https://discord.gg/NGYQh4aZ
