### ISSUE TITLE
Simpler test runner

### ISSUE THREAD

**Issue by chris-martin** [hedgehogqa/haskell-hedgehog#51]
The progress output is really pretty, but...

* It's not very useful if you have a large number of tests, since you can't see most of the output - and in tmux, at least, the progress updates only work on the last screenful of output.
* If I recall correctly, this sort of output doesn't get along very well with some CI systems.

Could there be a test runner that only prints failures (and maybe a total count at the end) and doesn't do fancy terminal rewriting?

**Comment by jystic** [comment]
> It's not very useful if you have a large number of tests, since you can't see most of the output

I agree this isn't ideal, the way that the tests which haven't run yet are displayed on the screen was a bit of an experiment. I plan to fix this up so that tests only appear in the list once they start running.

> and in tmux, at least, the progress updates only work on the last screenful of output.

That's a shame, I'll need to have a play with tmux and see if I can replicate it. The fact that terminal updates happen on a different thread can mean they get starved by running tests.

> If I recall correctly, this sort of output doesn't get along very well with some CI systems.

That case should be handled properly, colors and in-place console updating are disabled unless we're connected to a TTY.

> Could there be a test runner that only prints failures (and maybe a total count at the end) and doesn't do fancy terminal rewriting?

I think this is a good idea, I would use it for CI where personally I only care about failures. I like the updating output in GHCi because it tells me quickly whether I've created a generator which is generating too much and causing slow tests.

The implementation of this quiet mode is easy, but harder is how it is deciding how it is activated. I think this is likely a per-user option. I know a few people at who I work with that would probably use the quiet mode instead of the fancy updating option.

Right now I'm thinking of making it configurable in code via `checkGroup` and having `checkConcurrent` try to detect what to do by looking at an environment variable or a config file in the user's home directory.

If others have any thoughts, I'd be open to suggestions?
