### ISSUE TITLE
Generalise `property` function

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#59]
For Hspec integration I need to convert this code (using QuickCheck):
```
prop :: String -> prop -> Spec
prop str = Hspec.it str . QC.property
```
which works, because the type is:
```
QC.property :: QC.Testable prop => prop -> QC.Property
```
However, the Hedgehog equivalent doesn't work because the type is concrete:
```
Hedgehog.property :: Hedgehog.Test IO () -> Hedgehog.Property
```
Is this something that can be changed?

**Comment by jystic** [comment]
Hedgehog doesn't have the concept of a `Testable` type class, because there is no `Arbitrary` instance magic, so I don't think this is necessary.

You should be able to write all properties using the concrete `Test IO ()`.

The way to summon random data in Hedgehog is using `forAll` rather than `Arbitrary` instances:
```hs
forAll :: Gen m a -> Test m a
```

So given this, the type of the `prop` equivalent for Hedgehog should be:
```hs
prop :: String -> Hedgehog.Test IO () -> Spec
```

If I take one of the HSpec examples:
```hs
describe "read" $ do
  prop "is inverse to show" $
    \x -> (read . show) x == (x :: Int)
```
it would look like this in Hedgehog:
```hs
describe "read" $ do
  prop "is inverse to show" $ do
    x <- forAll $ Gen.int Range.linearBounded
    (read . show) x === x
```

**Comment by erikd** [comment]
You're right. Hspec using Hedgehog is going to look just a little different to QuickCheck, but who cares?
